apiVersion: v1
data:
  metabase-db-dbname: bW9iaWxpdHk=
  metabase-db-pass: dGVsZWNjaGlhcHBvbmU=
  metabase-db-type: cG9zdGdyZXM=
  metabase-db-user: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: null
  name: metabase-secret
