apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    run: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metabase
  template:
    metadata:
      generateName: metabase
      labels:
        run: metabase
    spec:
      restartPolicy: Always
      containers:
        - name: metabase
          image: metabase/metabase
          imagePullPolicy: Always
          ports:
            - name: metabase
              containerPort: 3000
          env:
            - name: MB_DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: metabase-db-type
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: metabase-db-dbname
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: metabase-db-pass
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: metabase-db-user
            - name: MB_DB_HOST
              value: db
      volumes:
        - name: metabase-secret
          secret:
            secretName: metabase-secret